# -*- coding: utf-8 -*-
"""data cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uEP9AXkDs2fxkJhcbYU96hsTTpDGm0DF
"""

# clean data from google sheet

from google.colab import auth
import gspread
from google.auth import default
import pandas as pd

#autenticating to google
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

#defining my worksheet
worksheet = gc.open('“印刷一场革命”投稿数据搜集 (Responses)').sheet1
#get_all_values gives a list of rows
rows = worksheet.get_all_values()
#Convert to a DataFrame 
df = pd.DataFrame(rows[1:], columns = rows[0])

# clean data
df.loc[df['caption'] == '', 'caption'] = df['请上传您的投稿文字']
df.loc[df['prompt'] == '', 'prompt'] = df['是什么启发了您的投稿？(e.g. 某个新闻事件）']
df = df.drop(labels = ['请上传您的投稿文字', '是什么启发了您的投稿？(e.g. 某个新闻事件）'], axis = 1)
df = df[df['consent'] == '同意']
df['image url'] = df['image url'].apply(lambda x: x.split(","))
df = df.explode('image url').reset_index()

df

from gspread_dataframe import set_with_dataframe
title = 'cleaned form data'
gc.create(title)  # if not exist
sheet = gc.open(title).sheet1
set_with_dataframe(sheet, df)

